"""remove changelog fk constraints

Revision ID: 2d522c9f9a16
Revises: b02cfc3722a7
Create Date: 2026-03-12 19:27:54.889454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d522c9f9a16'
down_revision: Union[str, None] = 'b02cfc3722a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changelogs', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('changelogs_experiment_id_fkey', 'changelogs', type_='foreignkey')
    op.drop_constraint('changelogs_before_snapshot_id_fkey', 'changelogs', type_='foreignkey')
    op.drop_constraint('changelogs_after_snapshot_id_fkey', 'changelogs', type_='foreignkey')
    op.drop_constraint('changelogs_product_id_fkey', 'changelogs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('changelogs_product_id_fkey', 'changelogs', 'products', ['product_id'], ['id'])
    op.create_foreign_key('changelogs_after_snapshot_id_fkey', 'changelogs', 'config_snapshots', ['after_snapshot_id'], ['id'])
    op.create_foreign_key('changelogs_before_snapshot_id_fkey', 'changelogs', 'config_snapshots', ['before_snapshot_id'], ['id'])
    op.create_foreign_key('changelogs_experiment_id_fkey', 'changelogs', 'experiments', ['experiment_id'], ['id'])
    op.alter_column('changelogs', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
