"""add_metric_tables

Revision ID: 8352594806d3
Revises: 2d522c9f9a16
Create Date: 2026-03-17 16:24:49.905174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8352594806d3'
down_revision: Union[str, None] = '2d522c9f9a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['metric_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checkpoint_type', sa.String(length=20), nullable=False),
    sa.Column('applicable_node_types', sa.JSON(), nullable=True),
    sa.Column('check_conditions', sa.JSON(), nullable=True),
    sa.Column('related_metrics', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('metric_definitions', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('metric_definitions', sa.Column('code', sa.String(length=50), nullable=False))
    op.add_column('metric_definitions', sa.Column('data_type', sa.String(length=20), nullable=False))
    op.add_column('metric_definitions', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('metric_definitions', sa.Column('applicable_node_types', sa.JSON(), nullable=True))
    op.add_column('metric_definitions', sa.Column('collection_method', sa.String(length=20), nullable=False))
    op.add_column('metric_definitions', sa.Column('collection_config', sa.JSON(), nullable=True))
    op.add_column('metric_definitions', sa.Column('aggregation_method', sa.String(length=20), nullable=False))
    op.add_column('metric_definitions', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('metric_definitions', sa.Column('thresholds', sa.JSON(), nullable=True))
    op.add_column('metric_definitions', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('metric_definitions', sa.Column('is_builtin', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'metric_definitions', ['code'])
    op.create_foreign_key(None, 'metric_definitions', 'metric_categories', ['category_id'], ['id'])
    op.drop_column('metric_definitions', 'node_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_definitions', sa.Column('node_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'metric_definitions', type_='foreignkey')
    op.drop_constraint(None, 'metric_definitions', type_='unique')
    op.drop_column('metric_definitions', 'is_builtin')
    op.drop_column('metric_definitions', 'sort_order')
    op.drop_column('metric_definitions', 'thresholds')
    op.drop_column('metric_definitions', 'weight')
    op.drop_column('metric_definitions', 'aggregation_method')
    op.drop_column('metric_definitions', 'collection_config')
    op.drop_column('metric_definitions', 'collection_method')
    op.drop_column('metric_definitions', 'applicable_node_types')
    op.drop_column('metric_definitions', 'unit')
    op.drop_column('metric_definitions', 'data_type')
    op.drop_column('metric_definitions', 'code')
    op.drop_column('metric_definitions', 'category_id')
    op.drop_table('milestones')
    op.drop_table('metric_categories')
    # ### end Alembic commands ###
