"""remove badcase fk constraints

Revision ID: b02cfc3722a7
Revises: 4acb41a1704c
Create Date: 2026-03-12 19:18:37.279625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02cfc3722a7'
down_revision: Union[str, None] = '4acb41a1704c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badcases', 'trace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('badcases', 'case_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('badcases', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('badcases_trace_id_fkey', 'badcases', type_='foreignkey')
    op.drop_constraint('badcases_case_id_fkey', 'badcases', type_='foreignkey')
    op.drop_constraint('badcases_experiment_id_fkey', 'badcases', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('badcases_experiment_id_fkey', 'badcases', 'experiments', ['experiment_id'], ['id'])
    op.create_foreign_key('badcases_case_id_fkey', 'badcases', 'cases', ['case_id'], ['id'])
    op.create_foreign_key('badcases_trace_id_fkey', 'badcases', 'traces', ['trace_id'], ['id'])
    op.alter_column('badcases', 'experiment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('badcases', 'case_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('badcases', 'trace_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
