"""add_agent_types_tables

Revision ID: c365ee3e6f64
Revises: 8352594806d3
Create Date: 2026-03-17 17:46:25.446302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c365ee3e6f64'
down_revision: Union[str, None] = '8352594806d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layer', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('execution_flow', sa.JSON(), nullable=True),
    sa.Column('io_definition', sa.JSON(), nullable=True),
    sa.Column('available_tools', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('agent_metric_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('weight_override', sa.Float(), nullable=True),
    sa.Column('thresholds_override', sa.JSON(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('collection_config_override', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_metric_mappings')
    op.drop_table('agent_types')
    # ### end Alembic commands ###
